"""initial schema

Revision ID: c8613139036b
Revises: 
Create Date: 2026-07-23 14:12:02.166176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c8613139036b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('accessibility_high_contrast', sa.Boolean(), nullable=False),
    sa.Column('accessibility_voice_output', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caregiver_links',
    sa.Column('subject_profile_id', sa.UUID(), nullable=False),
    sa.Column('caregiver_profile_id', sa.UUID(), nullable=True),
    sa.Column('invite_token', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REVOKED', name='caregiverlinkstatus', native_enum=False), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index(op.f('ix_caregiver_links_subject_profile_id'), 'caregiver_links', ['subject_profile_id'], unique=False)
    op.create_table('reference_appearances',
    sa.Column('ndc', sa.String(length=20), nullable=True),
    sa.Column('side', sa.Enum('FRONT', 'BACK', name='side', native_enum=False), nullable=False),
    sa.Column('imprint', sa.String(length=60), nullable=True),
    sa.Column('shape', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('size_mm', sa.Float(), nullable=True),
    sa.Column('scored', sa.Boolean(), nullable=False),
    sa.Column('image_uri', sa.String(length=500), nullable=False),
    sa.Column('origin', sa.Enum('LIBRARY', 'USER_ENROLLED', name='origin', native_enum=False), nullable=False),
    sa.Column('owner_profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_appearances_ndc'), 'reference_appearances', ['ndc'], unique=False)
    op.create_table('medications',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('strength', sa.String(length=60), nullable=True),
    sa.Column('form', sa.String(length=60), nullable=True),
    sa.Column('ndc', sa.String(length=20), nullable=True),
    sa.Column('appearance_front_id', sa.UUID(), nullable=True),
    sa.Column('appearance_back_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appearance_back_id'], ['reference_appearances.id'], ),
    sa.ForeignKeyConstraint(['appearance_front_id'], ['reference_appearances.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_ndc'), 'medications', ['ndc'], unique=False)
    op.create_index(op.f('ix_medications_profile_id'), 'medications', ['profile_id'], unique=False)
    op.create_table('schedules',
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('window_label', sa.String(length=40), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('days_of_week', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('dose_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_medication_id'), 'schedules', ['medication_id'], unique=False)
    op.create_table('dose_events',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scheduled_window_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.Enum('MATCH', 'MISMATCH', 'CANNOT_IDENTIFY', 'MANUAL_TAKEN', name='doseeventresult', native_enum=False), nullable=False),
    sa.Column('per_pill', sa.JSON(), nullable=False),
    sa.Column('quality', sa.JSON(), nullable=False),
    sa.Column('image_uri', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_window_id'], ['schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dose_events_profile_id'), 'dose_events', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dose_events_profile_id'), table_name='dose_events')
    op.drop_table('dose_events')
    op.drop_index(op.f('ix_schedules_medication_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_medications_profile_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_ndc'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_reference_appearances_ndc'), table_name='reference_appearances')
    op.drop_table('reference_appearances')
    op.drop_index(op.f('ix_caregiver_links_subject_profile_id'), table_name='caregiver_links')
    op.drop_table('caregiver_links')
    op.drop_table('profiles')
    # ### end Alembic commands ###
